version: '3'

services:
  backend:
    image: backend
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: flasksqlTest
    ports:
      - "5432:5432"

  debug_client:
    image: alpine
    command: tail -f /dev/null