version: '3'

services:
  backend:
    image: backend
    build: ./backend
    ports:
      - "9000:9000"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: flasksqlTest
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h localhost -d flasksqlTest" ]
      interval: 10s
      timeout: 5s
      retries: 3

  debug_client:
    image: alpine
    command: tail -f /dev/null