version: '3'

services:
  backend:
    image: backend
    build:
      context: ./backend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_EXPOSED_PORT}:${BACKEND_PORT}"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env

  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXPOSED_PORT}:${DB_PORT}"
    volumes:
      - database-data:${DB_VOL_PATH}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -h localhost -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database-data: