_format_version: "3.0"
_transform: true

consumers:
  - username: admin
    custom_id: admin
    keyauth_credentials:
      - key: admin
services:
  - host: backend
    name: flask
    port: 9000
    protocol: http
    routes:
      - name: flask
        paths:
          - /
      - name: options
        paths:
          - /api/v1/option/protected
        strip_path: true
        methods:
          - POST
          - DELETE
      - name: vote
        paths:
          - /api/v1/option/(?<id>\d+)/vote

plugins:
  - name: file-log
    config:
      path: /logs/file-log.log
      reopen: false

  - name: key-auth
    route: options
    config:
      key_in_header: true
      key_names:
        - apikey
      hide_credentials: false