# WIP
# terraform state rm aws_instance.bastion && terraform state rm null_resource.wait_for_bastion && terraform state rm null_resource.delete_bastion
# terraform import postgresql_database.polldb polldb && terraform import postgresql_database.kongdb kongdb && terraform import postgresql_role.app_user flask && terraform import postgresql_role.kong_user kong
# terraform state list | grep postgresql_ | xargs -I {} terraform state rm {}