name: CI/CD
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - main
  release:
    types:
      - created
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat .github/super-linter.env >> "$GITHUB_ENV"
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: develop
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Not implemented
        run: echo "This phase has not been implemented (yet)"
  build:
    name: Build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: make deps
      - name: Build React app
        run: make build-front
      - name: Build Docker image
        run: make build-image
      - name: Save Docker image
        run: make save-image
        env:
          FILE_NAME: docker-image
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ./docker-image.tar.gz
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .
      - name: Decompress Docker image
        run: gzip -d docker-image.tar.gz -c > docker-image.tar
      - name: Load Docker image
        run: docker load -i docker-image.tar
      - name: Push image
        run: make push-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_IMAGE_NAME: ${{ vars.AWS_IMAGE_NAME }}
  deploy-test:
    name: Deploy (test env)
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy to test env
        run: echo "This phase has not been implemented (yet)"
  deploy-prod:
    name: Deploy (production)
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
    needs:
      - publish
    steps:
      - name: Deploy ECR image
        run: echo "This phase has not been implemented (yet)"
